### PR TITLE
Add slugify file to remove underscore.string dependency

### PR DESCRIPTION
**Pull request by miduga**
Please, review @carlosvillu @nucliweb @kikoruiz @SUI-Components/developers 

In order to remove the big `underscore.string` I've extracted the important parts from the package and avoid loading the dependency to only slugify an url. Also I've added one more tests to it.

PS: Travis is giving me an error `travis_start_sauce_connect` but it has nothing to do with the tests. 🤔

### CODE REVIEW

**Comment by nucliweb** [comment]
👍

**Comment by miduga** [comment]
I've added a minor style commit for the return of the slug. ;)

**Comment by nucliweb** [comment]
🤔 You change the code after approved

**Comment by miduga** [comment]
Sorry @nucliweb :D I've added a comment here in order to keep you updated about my change. Anyway, please, go ahead and check it again! 🙇

**Comment by miduga** [comment]
@carlosvillu usted sabría decir por qué peta travis? :( no tengo mucha experiencia todavía con Travis!

**Comment by carlosvillu** [comment]
Peta por la API de source lab. Demasiadas peticiones. 
Deshabilitarlo Travis y mergea

**Pull request merged**
